"""
CardioAI Pro — Audit Compliance Report
==========================================
Combines the most recent bias audit result (fairness/bias_audit.py) with
live automation-tier operating stats into a single document — the kind of
artifact an FDA equity-guidance compliance review would actually want to
see, rather than making someone stitch together two separate API calls.

This report does not itself certify compliance. It assembles evidence a
real compliance process would review; "passes_equity_target" reflects
the bias audit's own pass/fail against the ≤2pp sensitivity-gap target,
nothing more.
"""
from __future__ import annotations

import time
from typing import Any, Optional


class ComplianceReportGenerator:
    def build(
        self, last_bias_audit: Optional[dict[str, Any]], orchestrator_stats: dict[str, Any],
    ) -> dict[str, Any]:
        if last_bias_audit is None:
            bias_section = {
                "status": "no_audit_run_yet",
                "note": "Run GET /api/bias-audit/run at least once — this report reflects the most recent result, not a live recomputation.",
            }
        else:
            bias_section = {
                "status": "pass" if last_bias_audit["overall_pass"] else "fail",
                "equity_target_pp": last_bias_audit["equity_target_pp"],
                "cohort_size": last_bias_audit["cohort_size"],
                "dimensions": {
                    dim: {
                        "passes": d["passes_equity_target"],
                        "baseline_sensitivity_gap_pp": d["baseline"]["sensitivity_gap_pp"],
                        "remediated_sensitivity_gap_pp": d["remediated"]["sensitivity_gap_pp"],
                    }
                    for dim, d in last_bias_audit["dimensions"].items()
                },
            }

        agent_health = [
            {"agent": a["name"], "runs": a["runs"], "error_rate": round(a["errors"] / a["runs"], 4) if a["runs"] else 0.0, "avg_latency_ms": a["avg_ms"]}
            for a in orchestrator_stats["agents"]
        ]

        return {
            "report_id": f"COMPLIANCE-{int(time.time())}",
            "generated_at": time.time(),
            "fda_equity_guidance": bias_section,
            "agent_health": agent_health,
            "note": (
                "This report is generated by the engine's own tooling for internal review. "
                "It is not a substitute for a formal regulatory audit or legal compliance sign-off."
            ),
        }
